import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='max-w-2xl mx-auto px-4'>
          <header className='flex justify-between items-center py-6 border-b'>
            <Link href={'/'} className='text-slate-800 text-2xl font-bold'>
              <h1>Projects list</h1>
            </Link>
            <Link
              href={'/create'}
              className='rounded-md text-blue-900 bg-blue-200 hover:bg-blue-300 px-3 py-2'
            >
              Create new project
            </Link>
          </header>
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
